export const FETCH_COLORS = "FETCH_COLORS";
export const CLEAR_COLOR_ARRAY = "CLEAR_COLOR_ARRAY";
export const UPDATE_APP_COLOR = "UPDATE_APP_COLOR";
export const UPDATE_COLOR_NAME = "UPDATE_COLOR_NAME";